### ISSUE TITLE
How to config

### ISSUE THREAD

**Issue by Spyro1502** [mantal/LC_SoundConfig#1]
Hi ! 
I just can't find how to config the sounds at all, and couldn't find any info about that

**Comment by mantal** [comment]
First you should launch the game with mod installed at least once.
Then if you use r2modman there is a tab on the left called "Config editor", open it and search for "SoundConfig".
Click on it, click on "Edit Config" and you will be able to set the volumes!
Make sure to save your change and restart the game and you will be all set :)
